### ISSUE TITLE
Per node-type permissions

### ISSUE THREAD

**Issue by hilmiller** [hpcsi/losf#40] opened 2014-08-21 13:37 UTC
I think the [Permissions] section should have the ability to define permissions per node type, just like the [Services] section. I hope this doesn't seem knit-picky, I'm wrestling with the fine-grained filesystem permissions of a hadoop cluster at the moment.

**Comment by koomie** [comment] 2015-03-30 22:34
This request is a duplicate of #66.

**Comment by koomie** [comment] 2015-03-30 22:35
Hil,

This feature has been added to the level branch and will be available in the forthcoming 0.51.0 release.

**Closed by koomie** 2015-03-30 22:35 UTC
