### ISSUE TITLE
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.

### ISSUE THREAD

**Issue by davidcarver** [hpcsi/losf#82] opened 2016-03-17 17:23 UTC
Using current losf-master (0.53)  zip file

login1.hikari(99)# vi /admin/build/admin/losf-master/config/config_dir

login1.hikari(101)# cat /admin/build/admin/losf-master/config/config_dir
/admin/build/admin/losf-master/config

login1.hikari(100)# /usr/local/adm/bin/sync_accounts.sh
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.
*\* Syncing configuration files (Hikari:login)
Can't use an undefined value as a HASH reference at /admin/build/admin/losf-master/utils/sync_config_utils.pl line 237.

  228      sub sync_const_file {
   229
   230          begin_routine();
   231
   232          my $file         = shift;       # input filename to sync
   233          my $cluster      = shift;       # cluster name
   234          my $type         = shift;       # node type
   235
   236          my $params       = shift;
  *\* 237          my %replace_vars = %$params;    # hash of variables to replace**
   238
   239          my $logr         = get_logger();
   240          my $found        = 0;
   241          my $customized   = 0;
   242
   243          my ($host_name,$doman_name) = query_local_network_name();

**Comment by davidcarver** [comment] 2016-03-17 17:47
By the way losf/update works!
but the following script fails call calls sync_config_files

# cat /usr/local/adm/bin/sync_accounts.sh

TOPDIR=/admin/build/admin/hpc_stack/
export OSF_ECHO_MODE=ERROR

delay=$(($RANDOM%8)) ; /bin/sleep $delay

$TOPDIR/sync_config_files /etc/passwd
$TOPDIR/sync_config_files /etc/shadow
$TOPDIR/sync_config_files /etc/group
$TOPDIR/sync_config_files /usr/local/etc/archive_dirs
$TOPDIR/sync_config_files /usr/local/etc/projectbalance.map
$TOPDIR/sync_config_files /usr/local/etc/project.map
$TOPDIR/sync_config_files /usr/local/etc/projectuser.map
$TOPDIR/sync_config_files /usr/local/etc/usage.map
$TOPDIR/sync_config_files /usr/local/etc/inactive.map

**Comment by koomie** [comment] 2017-06-01 19:35
Believe this is a duplicate of #85 that was resolved in devel branch.

**Closed by koomie** 2017-06-01 19:35 UTC
Labels: duplicate
